services:
  kafka:
    extends:
      service: kafka
      file: Kafka/compose.yaml
    env_file:
      - .env
    environment:
      - KAFKA_TOPIC_LOGS=${KAFKA_TOPIC_LOGS}
      - KAFKA_TOPIC_ALERTS=${KAFKA_TOPIC_ALERTS}
    post_start:
      - command: /bin/sh -c "/opt/kafka/bin/kafka-topics.sh --create --topic $KAFKA_TOPIC_LOGS --if-not-exists --bootstrap-server localhost:9092"
      - command: /bin/sh -c "/opt/kafka/bin/kafka-topics.sh --create --topic $KAFKA_TOPIC_ALERTS --if-not-exists --bootstrap-server localhost:9092"
  clickhouse:
    extends:
      service: clickhouse
      file: Clickhouse/compose.yaml
  ingestion_api:
    build:
      context: ../
      dockerfile: ./src/IngestionAPI/Dockerfile
    depends_on:
      - kafka
    env_file:
      - .env
    ports:
      - 8081:8080 #8080 is default aspnet image port exposed
  policy_engine:
    build:
      context: ../
      dockerfile: ./src/PolicyEngine/Dockerfile
    env_file:
      - .env
    depends_on:
      data_storage_worker:
        condition: service_started
  data_storage_worker:
    build:
      context: ../
      dockerfile: ./src/DataStorageService/Dockerfile
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      clickhouse:
        required: true
        condition: service_started
  actions_engine:
    build:
      context: ../
      dockerfile: ./src/ActionsEngine/Dockerfile
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
      policy_engine:
        condition: service_started